/******************************<<config wizard begin>>*************************
<group=pin>Pin used
      <list>TIM1_BKIN
           <DISABLE=>Disable
           <TIM1_BKIN=>Enable
           <code>$NOCODE$
      <list>TIM1_CH1N
           <DISABLE=>Disable
           <TIM1_CH1N=>Enable
           <code>$NOCODE$
      <list>TIM1_CH2N
           <DISABLE=>Disable
           <TIM1_CH2N=>Enable
           <code>$NOCODE$
      <list>TIM1_CH3N
           <DISABLE=>Disable
           <TIM1_CH3N=>Enable
           <code>$NOCODE$
      <list>TIM1_BKIN
           <DISABLE=>Disable
           <TIM1_BKIN=>Enable
           <code>$NOCODE$
      <list>TIM1_CH1N
           <DISABLE=>Disable
           <TIM1_CH1N=>Enable
           <code>$NOCODE$
      <list>TIM1_CH2N
           <DISABLE=>Disable
           <TIM1_CH2N=>Enable
           <code>$NOCODE$
      <list>TIM1_CH3N
           <DISABLE=>Disable
           <TIM1_CH3N=>Enable
           <code>$NOCODE$
      <list>TIM1_CH1
           <DISABLE=>Disable
           <TIM1_CH1=>Enable
           <code>$NOCODE$
      <list>TIM1_CH2
           <DISABLE=>Disable
           <TIM1_CH2=>Enable
           <code>$NOCODE$
      <list>TIM1_CH3
           <DISABLE=>Disable
           <TIM1_CH3=>Enable
           <code>$NOCODE$
      <list>TIM1_CH4
           <DISABLE=>Disable
           <TIM1_CH4=>Enable
           <code>$NOCODE$
      <list>TIM1_ETR
           <DISABLE=>Disable
           <TIM1_ETR=>Enable
           <code>$NOCODE$
</group>
******************************<<config wizard end>>***************************/
void TIM1_Init()
{
}
