/******************************<<config wizard begin>>*************************
<group=pin>Pin used
      <list>PB5
           <DISABLE=>Disable
           <PB5=>Enable
           <code>$NOCODE$
      <list>PB6
           <DISABLE=>Disable
           <PB6=>Enable
           <code>$NOCODE$
      <list>PC4
           <DISABLE=>Disable
           <PC4=>Enable
           <code>$NOCODE$
      <list>PB0
           <DISABLE=>Disable
           <PB0=>Enable
           <code>$NOCODE$
      <list>PB1
           <DISABLE=>Disable
           <PB1=>Enable
           <code>$NOCODE$
      <list>PB2
           <DISABLE=>Disable
           <PB2=>Enable
           <code>$NOCODE$
      <list>PB10
           <DISABLE=>Disable
           <PB10=>Enable
           <code>$NOCODE$
      <list>PB11
           <DISABLE=>Disable
           <PB11=>Enable
           <code>$NOCODE$
      <list>PB12
           <DISABLE=>Disable
           <PB12=>Enable
           <code>$NOCODE$
      <list>PB13
           <DISABLE=>Disable
           <PB13=>Enable
           <code>$NOCODE$
      <list>PB14
           <DISABLE=>Disable
           <PB14=>Enable
           <code>$NOCODE$
      <list>PB15
           <DISABLE=>Disable
           <PB15=>Enable
           <code>$NOCODE$
      <list>PB3
           <DISABLE=>Disable
           <PB3=>Enable
           <code>$NOCODE$
      <list>PB4
           <DISABLE=>Disable
           <PB4=>Enable
           <code>$NOCODE$
      <list>PB5
           <DISABLE=>Disable
           <PB5=>Enable
           <code>$NOCODE$
      <list>PB6
           <DISABLE=>Disable
           <PB6=>Enable
           <code>$NOCODE$
      <list>PB7
           <DISABLE=>Disable
           <PB7=>Enable
           <code>$NOCODE$
      <list>PB8
           <DISABLE=>Disable
           <PB8=>Enable
           <code>$NOCODE$
      <list>PB9
           <DISABLE=>Disable
           <PB9=>Enable
           <code>$NOCODE$
</group>
******************************<<config wizard end>>***************************/
void GPIOB_Init()
{
}
