/******************************<<config wizard begin>>*************************
<group=pin>Pin used
      <list>PD8
           <DISABLE=>Disable
           <PD8=>Enable
           <code>$NOCODE$
      <list>PD9
           <DISABLE=>Disable
           <PD9=>Enable
           <code>$NOCODE$
      <list>PD10
           <DISABLE=>Disable
           <PD10=>Enable
           <code>$NOCODE$
      <list>PD11
           <DISABLE=>Disable
           <PD11=>Enable
           <code>$NOCODE$
      <list>PD12
           <DISABLE=>Disable
           <PD12=>Enable
           <code>$NOCODE$
      <list>PD13
           <DISABLE=>Disable
           <PD13=>Enable
           <code>$NOCODE$
      <list>PD14
           <DISABLE=>Disable
           <PD14=>Enable
           <code>$NOCODE$
      <list>PD15
           <DISABLE=>Disable
           <PD15=>Enable
           <code>$NOCODE$
      <list>PD0
           <DISABLE=>Disable
           <PD0=>Enable
           <code>$NOCODE$
      <list>PD1
           <DISABLE=>Disable
           <PD1=>Enable
           <code>$NOCODE$
      <list>PD2
           <DISABLE=>Disable
           <PD2=>Enable
           <code>$NOCODE$
      <list>PD3
           <DISABLE=>Disable
           <PD3=>Enable
           <code>$NOCODE$
      <list>PD4
           <DISABLE=>Disable
           <PD4=>Enable
           <code>$NOCODE$
      <list>PD5
           <DISABLE=>Disable
           <PD5=>Enable
           <code>$NOCODE$
      <list>PD6
           <DISABLE=>Disable
           <PD6=>Enable
           <code>$NOCODE$
      <list>PD7
           <DISABLE=>Disable
           <PD7=>Enable
           <code>$NOCODE$
</group>
******************************<<config wizard end>>***************************/
void GPIOD_Init()
{
}
