/******************************<<config wizard begin>>*************************
<group=pin>Pin used
      <list>PC13
           <DISABLE=>Disable
           <PC13=>Enable
           <code>$NOCODE$
      <list>PC14
           <DISABLE=>Disable
           <PC14=>Enable
           <code>$NOCODE$
      <list>PC15
           <DISABLE=>Disable
           <PC15=>Enable
           <code>$NOCODE$
      <list>PC0
           <DISABLE=>Disable
           <PC0=>Enable
           <code>$NOCODE$
      <list>PC1
           <DISABLE=>Disable
           <PC1=>Enable
           <code>$NOCODE$
      <list>PC2
           <DISABLE=>Disable
           <PC2=>Enable
           <code>$NOCODE$
      <list>PC3
           <DISABLE=>Disable
           <PC3=>Enable
           <code>$NOCODE$
      <list>PC5
           <DISABLE=>Disable
           <PC5=>Enable
           <code>$NOCODE$
      <list>PC6
           <DISABLE=>Disable
           <PC6=>Enable
           <code>$NOCODE$
      <list>PC7
           <DISABLE=>Disable
           <PC7=>Enable
           <code>$NOCODE$
      <list>PC8
           <DISABLE=>Disable
           <PC8=>Enable
           <code>$NOCODE$
      <list>PC9
           <DISABLE=>Disable
           <PC9=>Enable
           <code>$NOCODE$
      <list>PC10
           <DISABLE=>Disable
           <PC10=>Enable
           <code>$NOCODE$
      <list>PC11
           <DISABLE=>Disable
           <PC11=>Enable
           <code>$NOCODE$
      <list>PC12
           <DISABLE=>Disable
           <PC12=>Enable
           <code>$NOCODE$
</group>
******************************<<config wizard end>>***************************/
void GPIOC_Init()
{
}
